"""INVARIANT: every criteria key a transform emits is defined, once, in the criteria-key registry.

THE RULE. A criteria key is a contract between three repos. Transformations emits it,
Integration-Service maps an integration's RTA row to it, and Token-Service extracts
transformedResponse[key] by exact, case-sensitive match and compares it against a requirement.
Categories have one authoritative definition (Integration-Service's IntegrationCategories,
GET /integration/enum/products). Criteria keys had none, which is how they drifted:
`isMFAEnabled` carries five incompatible meanings across eight integrations,
`requiredCoveragePercentage` is a boolean at two vendors and a percentage at ten, and
`isEPPConfigured` is a percentage at fourteen and a boolean at six -- so no requirement bar fits
both halves of the estate. contracts/criteria-registry/keys/<key>.json is that one definition.

WHAT THIS CHECKS, three things, each behind the same may-only-shrink ratchet the sibling
contracts use:

  1. SCHEMA. Every registry entry validates against criteria-key.schema.json, plus the rules
     a schema cannot express: the file is named after the key; names and aliases are unique
     case-insensitively (a one-letter case difference is a different key to Token-Service and
     the same file to a case-insensitive filesystem); validation.level is the MINIMUM across
     implementations; a deprecated key names a registered successor. Schema failures are never
     allowlisted -- a malformed entry is fixed, not waived.

  2. UNREGISTERED KEYS. Each transform under safeguards/ is executed in the production
     RestrictedPython sandbox against two bodies that carry no evidence -- {} and a body whose
     every read raises -- and the keys of the transformedResponse it returns are read OFF THE
     RESULT, never off the filename (`isssorequired.py` yields isSsorequired, never
     isSSORequired; the mapping is lossy). A criterion-shaped key (see _is_criterion_shaped)
     with no registry entry and no alias is a finding.

  3. TYPE. For a registered key whose status is not `contested`, every value observed on
     those bodies must be null or the declared valueType. A bool is not a number here, because
     Conditions.greaterThan coerces with int(float(x)) and int(float(False)) is 0 -- the exact
     mechanism by which an unreadable coverage figure clears a "fewer than N" bar. A contested
     key's type is NOT enforced (the registry has not ruled); its observed type split is
     printed instead, as evidence for whoever rules.

WHAT THIS DOES NOT CHECK, stated so a green run is not over-read:

  * Success-path values. The two bodies prove nothing, so a transform whose success branch
    returns a bool under a numeric key is invisible here (BeyondTrust and DopeSecurity's
    requiredCoveragePercentage are exactly that). Those are caught by the registry entry's
    replay-backed implementation records, not by CI.
  * Whether a registered key MEANS what its entry says. That is what the entry's citations and
    V-level are for. The registry's defence against a confident wrong entry is not the field;
    it is the evidence the field is required to cite.
  * Which integration may answer a key. That needs the RTA, which lives in Integration-Service;
    integrationPolicy/allowedIntegrations is enforced there (contracts/criteria-registry/
    README.md, "Who enforces what").

THE RATCHET. contracts/criteria-registry-allowlist.json is generated by --emit-allowlist, never
by hand, and MAY ONLY SHRINK. Instances are `<file>::<key>` (unregistered) and
`<file>::<key>::<type>` (type). A listed instance is reported and does not fail the run; an
unlisted one does; a listed one that no longer reproduces is reported STALE so the list keeps
moving. Registering a key is how its instances leave the list.

USAGE
    python tools/check_criteria_registry.py
    python tools/check_criteria_registry.py --self-test
    python tools/check_criteria_registry.py --emit-allowlist
    python tools/check_criteria_registry.py --schema-only
"""
from __future__ import annotations

import argparse
import json
import pathlib
import re
import signal
import sys
import warnings

ROOT = pathlib.Path(__file__).resolve().parent.parent
SAFEGUARDS = ROOT / "safeguards"
REGISTRY = ROOT / "contracts" / "criteria-registry"
KEYS_DIR = REGISTRY / "keys"
SCHEMA = REGISTRY / "criteria-key.schema.json"
ALLOWLIST = ROOT / "contracts" / "criteria-registry-allowlist.json"

#: Same floor the sibling checkers use. A walk that has collapsed and a clean tree both print
#: zero findings; refusing a short walk is the difference between them.
MIN_JUDGED_TRANSFORMS = 400

#: A transform that loops forever on a no-evidence body is reported, not waited on.
PER_TRANSFORM_SECONDS = 5

TEST_MODULE = re.compile(r"^(test_.*|.*_test|conftest)\.py$")

#: Verdict-shaped prefixes, as in check_no_self_answer.py, followed by an upper-case letter.
_VERDICT_PREFIXES = ("is", "are", "has", "can", "was", "should", "confirmed")
#: Value-shaped suffixes. A key spelled this way names a measurement with a unit.
_VALUE_SUFFIXES = ("Count", "Percentage", "Percent", "Rate", "Days", "Hours", "Minutes",
                   "Seconds", "Score", "Age")


def _is_criterion_shaped(name: str) -> bool:
    """Whether an emitted key is in scope for the unregistered-key rule.

    WHY A SHAPE AND NOT EVERY KEY. A transformedResponse carries its criteria keys next to
    working figures -- `error`, `reason`, `totalUsers`, `policiesJudged`. Measured on main
    2026-10-07: 1,637 distinct keys are emitted on the two no-evidence bodies, of which 234
    files emit `error` and 120 emit `reason`. Requiring a registry entry for `reason` would
    produce a checker nobody reads. The shape is what separates a verdict or a measurement
    from plumbing.

    WHAT THE SHAPE MISSES, measured rather than assumed: against the 485 keys production RTA
    rows actually map (QC snapshot 2026-10-06), this rule matches 460. The 25 it misses --
    `authTypesAllowed`, `legacyAuthBlocked`, `backupFrequency`, `noCriticalFindings` and
    others -- are still governed, because Integration-Service's check requires EVERY RTA key
    to be registered regardless of shape. This rule decides only what Transformations CI
    sees on its own; it is scope, not meaning.

    THIS IS NOT A LIST OF KEY NAMES. It does not decide whether anything was measured -- that
    is decided from the value (VALIDATION-GATE.md, 'Derive from the value'). It decides only
    which emitted names must have a definition.
    """
    if not name or not name.isidentifier() or "_" in name or len(name) < 5:
        return False
    if not name[0].islower():
        return False
    for p in _VERDICT_PREFIXES:
        if name.startswith(p) and len(name) > len(p) and name[len(p)].isupper():
            return True
    return name.endswith(_VALUE_SUFFIXES)


# ----------------------------------------------------------------------------- schema

class SchemaError(Exception):
    """The SCHEMA uses something this validator does not implement. Fatal, never a finding."""


#: Keywords this validator implements. Anything else in the schema is refused rather than
#: silently ignored -- an ignored keyword is a rule that looks enforced and is not.
_IMPLEMENTED = {
    "type", "enum", "const", "required", "properties", "additionalProperties", "items",
    "minItems", "uniqueItems", "minLength", "pattern", "minimum", "maximum", "$ref", "allOf",
    "if", "then", "else", "$defs",
}
_ANNOTATIONS = {"$schema", "$id", "title", "description", "$comment", "default", "examples"}

_JSON_TYPES = {
    "object": lambda v: isinstance(v, dict),
    "array": lambda v: isinstance(v, list),
    "string": lambda v: isinstance(v, str),
    "integer": lambda v: isinstance(v, int) and not isinstance(v, bool),
    "number": lambda v: isinstance(v, (int, float)) and not isinstance(v, bool),
    "boolean": lambda v: isinstance(v, bool),
    "null": lambda v: v is None,
}


def _resolve(root: dict, ref: str) -> dict:
    if not ref.startswith("#/"):
        raise SchemaError(f"only local $ref is supported, got {ref!r}")
    node = root
    for part in ref[2:].split("/"):
        node = node[part]
    return node


def validate(instance, schema: dict, root: dict | None = None, path: str = "$") -> list[str]:
    """Validate against the subset of JSON Schema 2020-12 this registry uses. Returns errors."""
    root = schema if root is None else root
    unknown = set(schema) - _IMPLEMENTED - _ANNOTATIONS
    if unknown:
        raise SchemaError(f"schema at {path} uses unimplemented keyword(s) {sorted(unknown)}")
    errs: list[str] = []
    if "$ref" in schema:
        errs += validate(instance, _resolve(root, schema["$ref"]), root, path)
    if "type" in schema:
        types = schema["type"] if isinstance(schema["type"], list) else [schema["type"]]
        if not any(_JSON_TYPES[t](instance) for t in types):
            return errs + [f"{path}: expected {'/'.join(types)}, got {type(instance).__name__}"]
    if "const" in schema and not _same(instance, schema["const"]):
        errs.append(f"{path}: must be {json.dumps(schema['const'])}")
    if "enum" in schema and not any(_same(instance, e) for e in schema["enum"]):
        errs.append(f"{path}: {json.dumps(instance)} not one of {schema['enum']}")
    if isinstance(instance, str):
        if len(instance) < schema.get("minLength", 0):
            errs.append(f"{path}: shorter than {schema['minLength']}")
        if "pattern" in schema and not re.search(schema["pattern"], instance):
            errs.append(f"{path}: {instance!r} does not match {schema['pattern']}")
    if _JSON_TYPES["number"](instance):
        if "minimum" in schema and instance < schema["minimum"]:
            errs.append(f"{path}: below minimum {schema['minimum']}")
        if "maximum" in schema and instance > schema["maximum"]:
            errs.append(f"{path}: above maximum {schema['maximum']}")
    if isinstance(instance, list):
        if len(instance) < schema.get("minItems", 0):
            errs.append(f"{path}: fewer than {schema['minItems']} item(s)")
        if schema.get("uniqueItems"):
            seen = [json.dumps(i, sort_keys=True) for i in instance]
            if len(seen) != len(set(seen)):
                errs.append(f"{path}: items are not unique")
        if "items" in schema:
            for i, item in enumerate(instance):
                errs += validate(item, schema["items"], root, f"{path}[{i}]")
    if isinstance(instance, dict):
        for req in schema.get("required", []):
            if req not in instance:
                errs.append(f"{path}: missing required '{req}'")
        props = schema.get("properties", {})
        for k, v in instance.items():
            if k in props:
                errs += validate(v, props[k], root, f"{path}.{k}")
            elif schema.get("additionalProperties") is False:
                errs.append(f"{path}: unexpected property '{k}'")
    for sub in schema.get("allOf", []):
        errs += validate(instance, sub, root, path)
    if "if" in schema:
        branch = "then" if not validate(instance, schema["if"], root, path) else "else"
        if branch in schema:
            errs += validate(instance, schema[branch], root, path)
    return errs


def _same(a, b) -> bool:
    """JSON equality: True is not 1, which Python's == would say it is."""
    if isinstance(a, bool) or isinstance(b, bool):
        return isinstance(a, bool) and isinstance(b, bool) and a == b
    return a == b


_LEVELS = ("V0", "V1", "V2", "V3")


def check_entries(entries: dict[str, dict], schema: dict) -> list[str]:
    """Schema plus the cross-field and cross-entry rules. `entries` maps filename stem -> entry."""
    errs: list[str] = []
    seen: dict[str, str] = {}
    for stem, entry in sorted(entries.items()):
        where = f"keys/{stem}.json"
        errs += [f"{where}: {e}" for e in validate(entry, schema)]
        if not isinstance(entry, dict):
            continue
        name = entry.get("name")
        if name != stem:
            errs.append(f"{where}: file is named '{stem}' but the entry is '{name}'")
        spellings = [name] + [a.get("name") for a in entry.get("aliases", []) if isinstance(a, dict)]
        for s in spellings:
            if not isinstance(s, str):
                continue
            folded = s.lower()
            if folded in seen and seen[folded] != stem:
                errs.append(f"{where}: '{s}' collides case-insensitively with an entry or alias "
                            f"in keys/{seen[folded]}.json")
            seen.setdefault(folded, stem)
        impls = (entry.get("validation") or {}).get("implementations") or []
        levels = [i.get("level") for i in impls if isinstance(i, dict) and i.get("level") in _LEVELS]
        expected = min(levels, key=_LEVELS.index) if levels else "V0"
        stated = (entry.get("validation") or {}).get("level")
        if stated in _LEVELS and stated != expected:
            errs.append(f"{where}: validation.level is {stated} but the minimum across "
                        f"implementations is {expected} -- one weak implementation holds the "
                        f"whole key down, in public")
        revs = [c.get("revision") for c in entry.get("changeLog", []) if isinstance(c, dict)]
        if revs and entry.get("revision") not in revs:
            errs.append(f"{where}: revision {entry.get('revision')} has no changeLog row")
    for stem, entry in sorted(entries.items()):
        succ = entry.get("deprecatedBy") if isinstance(entry, dict) else None
        if succ and succ not in entries:
            errs.append(f"keys/{stem}.json: deprecatedBy '{succ}' is not a registered key")
    return errs


def load_registry(keys_dir: pathlib.Path = KEYS_DIR) -> tuple[dict, list[str]]:
    entries, errs = {}, []
    for p in sorted(keys_dir.glob("*.json")) if keys_dir.is_dir() else []:
        try:
            entries[p.stem] = json.loads(p.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as e:
            errs.append(f"keys/{p.name}: not readable JSON: {e}")
    return entries, errs


def registered_spellings(entries: dict) -> dict[str, str]:
    """Every name and alias -> the canonical entry it resolves to."""
    out = {}
    for stem, e in entries.items():
        if not isinstance(e, dict):
            continue
        out[e.get("name", stem)] = stem
        for a in e.get("aliases", []):
            if isinstance(a, dict) and a.get("name"):
                out[a["name"]] = stem
    return out


# ----------------------------------------------------------------------------- emission

class _Poison(dict):
    """Every read raises. Forces a transform down its own except branch."""

    def get(self, *a, **k):
        raise RuntimeError("poisoned read")

    def __getitem__(self, k):
        raise RuntimeError("poisoned read")

    def keys(self):
        raise RuntimeError("poisoned read")

    def items(self):
        raise RuntimeError("poisoned read")


def _sandbox():
    sys.path.insert(0, str(ROOT / "tools"))
    import restricted_sandbox  # noqa: E402 -- needs RestrictedPython, which CI installs
    return restricted_sandbox


def _load_transform(sandbox, source: str, filename: str):
    # restricted_sandbox rejects leading-underscore names exactly as production does; these two
    # helpers are renamed the way probe_failure_channel.py renames them, so the walk judges the
    # files the pipeline can run rather than failing on a name the pipeline also rewrites.
    for name in ("_parse_input", "_listify"):
        source = re.sub(r"\b" + name + r"\b", name.lstrip("_") + "_sandboxed", source)
    return sandbox.load(source, filename=filename)["transform"]


class _Timeout(Exception):
    pass


def _alarm(_signum, _frame):
    raise _Timeout()


def emitted(fn) -> tuple[dict[str, list], str | None]:
    """{key: [values]} read off transformedResponse for the two no-evidence bodies.

    Returns (values, None) when at least one body produced a dict, else ({}, why).
    """
    values: dict[str, list] = {}
    why = None
    for body in ({}, _Poison()):
        try:
            if hasattr(signal, "SIGALRM"):
                signal.signal(signal.SIGALRM, _alarm)
                signal.alarm(PER_TRANSFORM_SECONDS)
            with warnings.catch_warnings():
                warnings.simplefilter("ignore")
                out = fn(body)
        except _Timeout:
            why = "timed out"
            continue
        except Exception as e:  # noqa: BLE001 -- a raising transform is reported, not fatal
            why = f"raised {type(e).__name__}"
            continue
        finally:
            if hasattr(signal, "SIGALRM"):
                signal.alarm(0)
        tr = out.get("transformedResponse", out) if isinstance(out, dict) else None
        if not isinstance(tr, dict):
            why = why or "returned no dict"
            continue
        for k, v in tr.items():
            if isinstance(k, str):
                values.setdefault(k, []).append(v)
    return (values, None) if values else ({}, why or "returned an empty dict")


def _json_type(v) -> str:
    if v is None:
        return "null"
    if isinstance(v, bool):
        return "boolean"
    if isinstance(v, int):
        return "integer"
    if isinstance(v, float):
        return "number"
    if isinstance(v, str):
        return "string"
    return type(v).__name__


def _type_ok(declared: str, v) -> bool:
    if v is None:
        return True
    t = _json_type(v)
    if declared == "number":
        return t in ("integer", "number")
    return t == declared


def judge(values: dict[str, list], spellings: dict[str, str], entries: dict,
          rel: str) -> tuple[set[str], set[str], dict[str, set[str]]]:
    """(unregistered instances, type instances, {contested key: observed types}) for one file."""
    unregistered, typed, contested = set(), set(), {}
    for key, vals in values.items():
        if key not in spellings:
            if _is_criterion_shaped(key):
                unregistered.add(f"{rel}::{key}")
            continue
        entry = entries[spellings[key]]
        declared = entry.get("valueType")
        if entry.get("status") == "contested" or declared == "unresolved":
            contested.setdefault(spellings[key], set()).update(
                _json_type(v) for v in vals if v is not None)
            continue
        for v in vals:
            if not _type_ok(declared, v):
                typed.add(f"{rel}::{key}::{_json_type(v)}")
    return unregistered, typed, contested


def transform_files(base: pathlib.Path = SAFEGUARDS) -> list[pathlib.Path]:
    return sorted(
        p for p in base.rglob("*.py")
        if not TEST_MODULE.match(p.name) and p.name != "__init__.py" and "schemas" not in p.parts
    )


def census(entries: dict) -> dict:
    sandbox = _sandbox()
    spellings = registered_spellings(entries)
    unregistered, typed, contested, not_judged = set(), set(), {}, {}
    judged = 0
    files = transform_files()
    for p in files:
        rel = str(p.relative_to(ROOT))
        try:
            fn = _load_transform(sandbox, p.read_text(encoding="utf-8"), p.name)
        except Exception as e:  # noqa: BLE001
            not_judged[rel] = f"does not load in the sandbox ({type(e).__name__})"
            continue
        values, why = emitted(fn)
        if why:
            not_judged[rel] = why
            continue
        judged += 1
        u, t, c = judge(values, spellings, entries, rel)
        unregistered |= u
        typed |= t
        for k, ts in c.items():
            contested.setdefault(k, {}).setdefault(rel, set()).update(ts)
    return {"unregistered": unregistered, "type": typed, "contested": contested,
            "not_judged": not_judged, "judged": judged, "examined": len(files)}


# ----------------------------------------------------------------------------- ratchet

def load_allowlist() -> dict:
    if not ALLOWLIST.is_file():
        return {"unregistered": [], "type": []}
    return json.loads(ALLOWLIST.read_text())


def emit_allowlist(result: dict) -> dict:
    out = {
        "contract": "criteria-registry",
        "why": "every criterion-shaped key a transform emits must have an entry in "
               "contracts/criteria-registry/keys/, and a registered key must be emitted as its "
               "declared type or null; this list may only shrink",
        "generated_by": "tools/check_criteria_registry.py --emit-allowlist",
        "how_to_shrink": "register the key (contracts/criteria-registry/keys/<key>.json) with "
                         "what is evidenced and \"unknown\" for what is not, or stop emitting it. "
                         "Never add to this list by hand.",
        "count": {"unregistered": len(result["unregistered"]), "type": len(result["type"])},
        "unregistered": sorted(result["unregistered"]),
        "type": sorted(result["type"]),
    }
    ALLOWLIST.parent.mkdir(parents=True, exist_ok=True)
    ALLOWLIST.write_text(json.dumps(out, indent=2) + "\n")
    return out


def _report_ratchet(label: str, found: set[str], allowed: set[str], hint: str) -> int:
    new = sorted(found - allowed)
    stale = sorted(allowed - found)
    print(f"{len(found)} {label} instance(s) ({len(new)} outside the allowlist)")
    if stale:
        print(f"\nSTALE {label} allowlist entries ({len(stale)}) -- no longer reproduce; "
              f"remove to let the ratchet shrink:")
        for s in stale:
            print(f"  {s}")
    if new:
        print(f"\n✗ {len(new)} {label} instance(s) not on the allowlist:")
        for s in new:
            print(f"  {s}")
        print(f"\n{hint}")
        return 1
    return 0


# ----------------------------------------------------------------------------- self-test

def _entry(name: str, **over) -> dict:
    e = {
        "name": name, "revision": 1, "status": "active",
        "definition": "A planted entry used only by the self-test.",
        "valueType": "boolean", "unit": "none", "population": "unknown",
        "polarity": "good_when_true", "evidenceRequiredForTrue": "unknown",
        "evidenceClass": "unknown",
        "notMeasured": {"value": None, "envelope": 'additionalInfo.dataCollection.status == "error"'},
        "emptyPopulationMeans": "undecided", "allowedCategories": [], "integrationPolicy": "any",
        "allowedIntegrations": [], "aliases": [], "owner": "unknown",
        "validation": {"level": "V0", "implementations": []},
        "citations": ["self-test"],
        "changeLog": [{"revision": 1, "date": "2026-10-07", "change": "planted"}],
    }
    e.update(over)
    return e


def _impl(level: str) -> dict:
    return {"integration": {"srn": "00000000-0000-0000-0000-000000000000", "name": "Planted"},
            "transform": "safeguards/planted.py", "level": level,
            "notMeasuredConformance": {"paths": {"refusal": "unverified", "emptyBody": "unverified",
                                                 "poisoned": "unverified"}}}


def self_test() -> int:
    """Plant defects AND the shapes that merely look like defects.

    The second half matters more. A checker tested only against a defect passes whatever it was
    going to pass; asserting what it must NOT flag is what makes this a test rather than a
    snapshot (VALIDATION-GATE.md, 'A checker's test must assert what it does NOT flag').
    """
    schema = json.loads(SCHEMA.read_text())
    bad = 0

    def expect(name: str, got: bool, want: bool, detail=""):
        nonlocal bad
        if got != want:
            bad += 1
            print(f"  FAIL self-test: {name} {detail}")
        else:
            print(f"  ok: {name}")

    contested_conflict = {
        "summary": "Two planted positions that disagree on the type.",
        "positions": [
            {"meaning": "a boolean", "valueType": "boolean", "source": "self-test",
             "integrations": [{"srn": "00000000-0000-0000-0000-000000000001", "name": "Planted A"}]},
            {"meaning": "a percentage", "valueType": "number", "source": "self-test",
             "integrations": [{"srn": "00000000-0000-0000-0000-000000000002", "name": "Planted B"}]},
        ],
        "decision": {"owner": "J.J.", "status": "open",
                     "question": "Which of the two planted positions is the key?"},
    }
    schema_cases = [
        ("a well-formed entry is accepted", {"isPlantedEnabled": _entry("isPlantedEnabled")}, True),
        ("a missing definition is rejected",
         {"isPlantedEnabled": {k: v for k, v in _entry("isPlantedEnabled").items()
                               if k != "definition"}}, False),
        ("notMeasured.value false is rejected -- null is pinned",
         {"isPlantedEnabled": _entry("isPlantedEnabled", notMeasured={
             "value": False, "envelope": 'additionalInfo.dataCollection.status == "error"'})}, False),
        ("contested without a conflict block is rejected",
         {"plantedPercentage": _entry("plantedPercentage", status="contested",
                                      valueType="unresolved", unit="unknown")}, False),
        ("contested WITH a conflict block is accepted",
         {"plantedPercentage": _entry("plantedPercentage", status="contested",
                                      valueType="unresolved", unit="unknown",
                                      conflict=contested_conflict)}, True),
        ("unresolved type on an active key is rejected",
         {"plantedPercentage": _entry("plantedPercentage", valueType="unresolved",
                                      unit="unknown")}, False),
        ("a boolean with a percent unit is rejected",
         {"isPlantedEnabled": _entry("isPlantedEnabled", unit="percent")}, False),
        ("listed policy with no integrations is rejected",
         {"isPlantedEnabled": _entry("isPlantedEnabled", integrationPolicy="listed")}, False),
        ("validation.level above the weakest implementation is rejected",
         {"isPlantedEnabled": _entry("isPlantedEnabled", validation={
             "level": "V3", "implementations": [_impl("V3"), _impl("V0")]})}, False),
        ("validation.level equal to the weakest implementation is accepted",
         {"isPlantedEnabled": _entry("isPlantedEnabled", validation={
             "level": "V1", "implementations": [_impl("V3"), _impl("V1")]})}, True),
        ("a file named for a different key is rejected",
         {"isPlantedOn": _entry("isPlantedEnabled")}, False),
        ("a case-only alias collision across entries is rejected",
         {"isPlantedEnabled": _entry("isPlantedEnabled"),
          "isPlantedImmutable": _entry("isPlantedImmutable", aliases=[
              {"name": "IsPlantedEnabled", "note": "case variant"}])}, False),
        ("deprecatedBy an unregistered key is rejected",
         {"isPlantedEnabled": _entry("isPlantedEnabled", status="deprecated",
                                     deprecatedBy="isNothingRegistered")}, False),
    ]
    for name, entries, ok in schema_cases:
        errs = check_entries(entries, schema)
        expect(name, not errs, ok, f"-> {errs[:2]}")

    try:
        validate({}, {"oneOf": []})
        expect("an unimplemented schema keyword is refused, not ignored", False, True)
    except SchemaError:
        expect("an unimplemented schema keyword is refused, not ignored", True, True)

    entries = {
        "isPlantedEnabled": _entry("isPlantedEnabled"),
        "plantedCoveragePercentage": _entry("plantedCoveragePercentage", valueType="number",
                                            unit="percent", polarity="higher_is_better",
                                            aliases=[{"name": "plantedCoveragePct",
                                                      "note": "old spelling"}]),
        "plantedContestedPercentage": _entry("plantedContestedPercentage", status="contested",
                                             valueType="unresolved", unit="unknown",
                                             conflict=contested_conflict),
    }
    spellings = registered_spellings(entries)
    emission_cases = [
        ("a registered boolean returning False is not flagged",
         {"isPlantedEnabled": [False]}, set(), set()),
        ("an unregistered verdict-shaped key is flagged",
         {"isPlantedAbsent": [False]}, {"f.py::isPlantedAbsent"}, set()),
        ("an unregistered value-shaped key is flagged",
         {"plantedAbsentCount": [None]}, {"f.py::plantedAbsentCount"}, set()),
        ("working figures are NOT flagged: error, reason, totalUsers, issues",
         {"error": ["x"], "reason": ["y"], "totalUsers": [0], "issues": [[]]}, set(), set()),
        ("an alias resolves to its entry and is not flagged",
         {"plantedCoveragePct": [None]}, set(), set()),
        ("a bool under a numeric key IS flagged -- int(float(False)) is 0",
         {"plantedCoveragePercentage": [False]}, set(),
         {"f.py::plantedCoveragePercentage::boolean"}),
        ("None under a numeric key is NOT flagged -- it is the pinned not-measured value",
         {"plantedCoveragePercentage": [None]}, set(), set()),
        ("an integer under a number key is NOT flagged",
         {"plantedCoveragePercentage": [0]}, set(), set()),
        ("a contested key's type is NOT enforced",
         {"plantedContestedPercentage": [False, 50]}, set(), set()),
    ]
    for name, values, want_u, want_t in emission_cases:
        u, t, _ = judge(values, spellings, entries, "f.py")
        expect(name, (u, t) == (want_u, want_t), True, f"-> {sorted(u)} {sorted(t)}")

    _, _, c = judge({"plantedContestedPercentage": [False, 50]}, spellings, entries, "f.py")
    expect("a contested key's observed types are reported as evidence",
           c == {"plantedContestedPercentage": {"boolean", "integer"}}, True, f"-> {c}")

    for k, want in (("isFirewallEnabled", True), ("requiredCoveragePercentage", True),
                    ("criticalVulnerabilityCount", True), ("issues", False), ("island", False),
                    ("totalUsers", False), ("CIScompliancePercentage", False), ("error", False)):
        expect(f"shape of {k!r} is {'in' if want else 'out of'} scope",
               _is_criterion_shaped(k), want)

    try:
        sandbox = _sandbox()
        fn = _load_transform(sandbox, "def transform(input):\n"
                             "    data = input if isinstance(input, dict) else {}\n"
                             "    return {'isPlantedEnabled': bool(data.get('x')), 'reason': 'r'}\n",
                             "planted.py")
        values, why = emitted(fn)
        expect("keys are read off the sandboxed transform's result, on both bodies",
               values.get("isPlantedEnabled") == [False] and why is None, True,
               f"-> {values} {why}")
        fn = _load_transform(sandbox, "def transform(input):\n    raise ValueError('x')\n",
                             "raises.py")
        values, why = emitted(fn)
        expect("a transform raising on both bodies is NOT JUDGED, not silently clean",
               (values, why) == ({}, "raised ValueError"), True, f"-> {values} {why}")
    except ImportError:
        print("  FAIL self-test: RestrictedPython is not installed; the census cannot run")
        bad += 1

    if bad:
        print(f"\n✗ {bad} self-test(s) failed -- the checker cannot be trusted")
        return 1
    print("\n✓ self-tests pass")
    return 0


# ----------------------------------------------------------------------------- main

def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--self-test", action="store_true")
    ap.add_argument("--emit-allowlist", action="store_true")
    ap.add_argument("--schema-only", action="store_true",
                    help="validate the registry entries and stop; needs no RestrictedPython")
    a = ap.parse_args()

    if a.self_test:
        return self_test()

    schema = json.loads(SCHEMA.read_text())
    entries, load_errs = load_registry()
    errs = load_errs + check_entries(entries, schema)
    contested = sorted(k for k, e in entries.items() if isinstance(e, dict)
                       and e.get("status") == "contested")
    print(f"{len(entries)} registry entr{'y' if len(entries) == 1 else 'ies'} "
          f"({len(contested)} contested)")
    if errs:
        print(f"\n✗ {len(errs)} registry entry error(s). These are never allowlisted:")
        for e in errs:
            print(f"  {e}")
        return 1
    print("✓ every entry validates against criteria-key.schema.json")
    if a.schema_only:
        return 0

    result = census(entries)
    if a.emit_allowlist:
        out = emit_allowlist(result)
        print(f"wrote {out['count']['unregistered']} unregistered and {out['count']['type']} "
              f"type instance(s) to {ALLOWLIST.relative_to(ROOT)}")
        return 0

    if result["judged"] < MIN_JUDGED_TRANSFORMS:
        print(f"✗ only {result['judged']} transform(s) judged, below the floor of "
              f"{MIN_JUDGED_TRANSFORMS}. A collapsed walk is refused rather than reported as a "
              "pass, because a clean tree and a tree this checker has stopped reading both "
              "print zero findings.")
        return 1

    keys = {i.split("::")[1] for i in result["unregistered"]}
    print(f"{result['examined']} transform file(s) examined, {result['judged']} judged, "
          f"{len(result['not_judged'])} not judged (raised, timed out or returned no dict on "
          f"both no-evidence bodies); {len(keys)} distinct unregistered criterion-shaped key(s)")
    for k in contested:
        by_file = result["contested"].get(k, {})
        split = sorted({t for ts in by_file.values() for t in ts})
        print(f"  contested {k}: {len(by_file)} file(s) emit it; non-null types observed on "
              f"no-evidence bodies: {split or ['none']} -- type not enforced until the registry "
              f"rules (keys/{k}.json, conflict.decision)")

    allow = load_allowlist()
    rc = _report_ratchet(
        "unregistered", result["unregistered"], set(allow.get("unregistered", [])),
        "Register each key in contracts/criteria-registry/keys/<key>.json before emitting it. "
        "Write what you can evidence and \"unknown\" (V0) for what you cannot; the schema's "
        "descriptions say what each field means.")
    rc |= _report_ratchet(
        "type", result["type"], set(allow.get("type", [])),
        "A registered key must be emitted as its declared valueType, or null when not measured "
        "(with additionalInfo.dataCollection.status \"error\"). See the key's entry.")
    if not rc:
        print("\n✓ no unallowlisted unregistered key and no unallowlisted type violation")
    return rc


if __name__ == "__main__":
    sys.exit(main())
